TEST-RSC-DIR                     = TESTS
TEST-TYPES                       = PHASE1_AND_PHASE2
TEST-SOURCES                     = ITSQ
MAX_CUSTOMERS_PER_TEST           = 8
ADMIN_FUNCS_ENABLED              = true
MUST_EXTEND_ENTGS_FROM_REST      = false
ITSQ_TAG_NAME_FORMAT             = USER-ENV-DATE-TIME
ITSQ_REVISIONS                   = ZWEI_PHASEN

USE_LOCAL_EXPORTS                = false
SFTP_UPLOAD_ACTIVE               = true
CHECK-EXPORT-PROTOKOLL-ACTIVE    = true

TIME_BEFORE_EXPORTS_COLLECT      = PT30S
TIME_BEFORE_SFTP_COLLECT         = PT1M
TIME_BEFORE_BTLG_IMPORT          = PT6M
TIME_BEFORE_CT_IMPORT            = PT1M
TIME_BEFORE_EXPORT               = PT6M
TIME_BEFORE_INSO_EXPORTS         = PT5S
IMPORT_CYCLE_TIME_OUT            = PT120M
STAGING_TIME_OUT                 = PT5M
STAGING_SLEEP_TIME               = PT10S
EXPORTS_TIME_OUT                 = PT10M
JOBSTATUS_QUERY_SLEEPTIME        = PT10S
JOB_START_DELAY_TIME             = PT5S
JOB_START_TIME_OUT               = PT5M
TARGET_CLZ_FOR_DE_PSEUDO_CREFOS  = 412
TARGET_CLZ_FOR_AT_PSEUDO_CREFOS  = 912
TARGET_CLZ_FOR_LU_PSEUDO_CREFOS  = 938
EXTRA_CLZS_TO_VC_LIST            = 912,938
IGNORABLE-XPATHS                 = firma-bonitaet/ratingstufe;auftrags-referenz;identification-number;/vsh-firmendatenexport/vsh-firmendaten/korrespondenz-adresse/hausnummer;vsh-firmendatenexport/vsh-firmendaten/bonitaet/bonitaets-index;/vsh-firmendatenexport[1]/vsh-firmendaten[1]/statistik[1]/letzte-aenderung[1]/text()[1]

ACTIVITI_URLS                    = CAVDARK-ABE@cavdark::http://rhsctear01.ecofis.de:9990;CAVDARK-ABE@cavdark::http://rhsctew003.ecofis.de:9999
MASTERKONSOLE_URLS               = tesuntestabe@tesuntestabe::http://wlsproxy.abe.creditreform.de:7001
BATCH_GUI_URLS                   = http://ctebatchgui.abe.verband.creditreform.de:7071
JVM_IMPCYCLE_URLS                = http://jvm02.abe.verband.creditreform.de:7051
JVM_INSO_URLS                    = http://jvm30.abe.verband.creditreform.de:7079
JVM_INSOBACKEND_URLS             = http://jvm31.abe.verband.creditreform.de:7080
JVM_BIC_URLS                     = http://jvm34.abe.verband.creditreform.de:7083

ACTIVITI-TESTER-EMAIL-FROM       = test-automatisierung@creditreform.de
ACTIVITI-TESTER-EMAIL-SUCCESS-TO = k.cavdar@verband.creditreform.de,n.nellen@verband.creditreform.de,u.ludwig@verband.creditreform.de
ACTIVITI-TESTER-EMAIL-FAILURE-TO = k.cavdar@verband.creditreform.de,n.nellen@verband.creditreform.de,u.ludwig@verband.creditreform.de
ACTIVITI-PROCESS-NAME            = ABE-TestAutomationProcess
ACTIVITI-PROCESS-TO-UPLOAD       = false
JOB-NAME-IMPORT-CYCLE            = IMPORTCYCLE;importcycle.importCycle;BETEILIGUNGEN_IMPORT,ENTSCHEIDUNGSTRAEGER_BERECHNUNG,BTLG_UPDATE_TRIGGER,FROM_STAGING_INTO_CTE
JOB-NAME-BTLG-IMPORT-DELTA       = IMPORTCYCLE;importcycle.beteiligungenImportDelta;BETEILIGUNGEN_IMPORT
JOB-NAME-ENTG-BERECHNUNG         = IMPORTCYCLE;importcycle.entgBerechnung;ENTSCHEIDUNGSTRAEGER_BERECHNUNG
JOB-NAME-BTLG-AKTUALISIERUNG     = IMPORTCYCLE;importcycle.btlnAktualisierung;BTLG_UPDATE_TRIGGER
JOB-NAME-CT-IMPORT-DELTA         = IMPORTCYCLE;importcycle.ctImportDelta;FROM_STAGING_INTO_CTE

JVM-BIC-URI                      = http://jvm34.abe.verband.creditreform.de:7083
JVM_BIC-USERNAME                 = tesuntestabe
JVM_BIC-PASSWORD                 = tesuntestabe
DHL_EXPORT_SFTP_HOST             = seread:liesmalABN@nfs.abe.ecofis.de
DHL_UPLOAD_SFTP_HOST             = seread:liesmalABN@sftp.cte-extern.abe.creditreform.de
DHL_TO_VVC_SFTP_PATH             = dhl/abnahme/dhl_to_vvc
VVC_TO_DHL_SFTP_PATH             = dhl/abnahme/vvc_to_dhl
DHL_EXPORT_PREFIX                = bic/export/delta
credentials-tuv105d560.ecofis.de    = seread@liesmalABN
password-ftp.cte-ikaros.abe.creditreform.de = seread@liesmalABN
password-drd2-ftp.abz.ecofis.de = seread@????
password-sftp.cte-extern.abe.creditreform.de = seread@liesmalABN
password-sftp.cte-intern.abe.creditreform.de = seread@liesmalABN

AVAILABLE_CUSTOMERS               = c01,c02,c03,c04
#                                  CustomerName;                JvmName;    ExportJobName;              UploadJobName;          ProcessIdentifier;      VcListPropName
#                                  --------------------------   ----------  -------------------------   ---------------------   -----------------
CUSTOMER_C01                     = C01;                         C01;        c01.deltaExport;            c01.deltaUpload;        EXPORT_CTE_TO_C01;      c01export
CUSTOMER_C02                     = C02;                         C02;        c02.deltaExport;            c02.deltaUpload;        EXPORT_CTE_TO_C02;      c02export
CUSTOMER_C03                     = C03;                         C03;        c03.deltaExport;            c03.deltaUpload;        EXPORT_CTE_TO_C03;      c03export
CUSTOMER_C04                     = C04;                         C04;        c04.deltaExport;            c04.deltaUpload;        EXPORT_CTE_TO_C04;      c04export
LAST_TEST_SOURCE = ITSQ
LAST_ITSQ_REVISION = ZWEI_PHASEN
LAST_UPLOAD_SYNTHETICS = false
LAST_USE_ONLY_TEST_CLZ = true
LAST_LOOK_AND_FEEL_CLASS = javax.swing.plaf.metal.MetalLookAndFeel
