TEST-RSC-DIR                     = X-TESTS
TEST-TYPES                       = PHASE1_AND_PHASE2
TEST-SOURCES                     = ITSQ
MAX_CUSTOMERS_PER_TEST           = 8
ADMIN_FUNCS_ENABLED              = true
MUST_EXTEND_ENTGS_FROM_REST      = false
ITSQ_TAG_NAME_FORMAT             = USER-ENV-DATE-TIME
ITSQ_REVISIONS                   = ZWEI_PHASEN

USE_LOCAL_EXPORTS                = false
SFTP_UPLOAD_ACTIVE               = true
CHECK-EXPORT-PROTOKOLL-ACTIVE    = true

TIME_BEFORE_EXPORTS_COLLECT      = PT1S
TIME_BEFORE_SFTP_COLLECT         = PT1S
TIME_BEFORE_BTLG_IMPORT          = PT1S
TIME_BEFORE_CT_IMPORT            = PT1S
TIME_BEFORE_EXPORT               = PT1S
TIME_BEFORE_INSO_EXPORTS         = PT1S
IMPORT_CYCLE_TIME_OUT            = PT15S
STAGING_TIME_OUT                 = PT10S
STAGING_SLEEP_TIME               = PT2S
EXPORTS_TIME_OUT                 = PT5S
JOBSTATUS_QUERY_SLEEPTIME        = PT1S
JOB_START_DELAY_TIME             = PT1S
JOB_START_TIME_OUT               = PT10S
TARGET_CLZ_FOR_DE_PSEUDO_CREFOS  = 412
TARGET_CLZ_FOR_AT_PSEUDO_CREFOS  = 912
TARGET_CLZ_FOR_LU_PSEUDO_CREFOS  = 938
EXTRA_CLZS_TO_VC_LIST            = 912,938
IGNORABLE-XPATHS                 = firma-bonitaet/ratingstufe;auftrags-referenz;identification-number;/vsh-firmendatenexport/vsh-firmendaten/korrespondenz-adresse/hausnummer;vsh-firmendatenexport/vsh-firmendaten/bonitaet/bonitaets-index;/vsh-firmendatenexport[1]/vsh-firmendaten[1]/statistik[1]/letzte-aenderung[1]/text()[1]

MASTERKONSOLE_URLS               = test@test::http://cavdar.de:7001
BATCH_GUI_URLS                   = test@test::http://cavdar.de:7001
JVM_IMPCYCLE_URLS                = test@test::http://cavdar.de:7001
JVM_INSO_URLS                    = test@test::http://cavdar.de:7001
JVM_INSOBACKEND_URLS             = test@test::http://cavdar.de:7001
JVM_BIC_URLS                     = test@test::http://cavdar.de:7001

STATE-ENGINE-EMAIL-FROM          = test-automatisierung@creditreform.de
STATE-ENGINE-EMAIL-SUCCESS-TO    = kemal@cavdar.de
STATE-ENGINE-EMAIL-FAILURE-TO    = kemal@cavdar.de
EMAIL-SMTP-HOST                  = localhost
EMAIL-SMTP-PORT                  = 2525
STATE-ENGINE-PROCESS-NAME        = GEE-TestAutomationProcess
JOB-NAME-IMPORT-CYCLE            = IMPORTCYCLE;importcycle.importCycle;BETEILIGUNGEN_IMPORT,ENTSCHEIDUNGSTRAEGER_BERECHNUNG,BTLG_UPDATE_TRIGGER,FROM_STAGING_INTO_CTE
JOB-NAME-BTLG-IMPORT-DELTA       = IMPORTCYCLE;importcycle.beteiligungenImportDelta;BETEILIGUNGEN_IMPORT
JOB-NAME-ENTG-BERECHNUNG         = IMPORTCYCLE;importcycle.entgBerechnung;ENTSCHEIDUNGSTRAEGER_BERECHNUNG
JOB-NAME-BTLG-AKTUALISIERUNG     = IMPORTCYCLE;importcycle.btlnAktualisierung;BTLG_UPDATE_TRIGGER
JOB-NAME-CT-IMPORT-DELTA         = IMPORTCYCLE;importcycle.ctImportDelta;FROM_STAGING_INTO_CTE

JVM-BIC-URI                      = ???
JVM_BIC-USERNAME                 = ???
JVM_BIC-PASSWORD                 = ???
DHL_EXPORT_SFTP_HOST             = ???
DHL_UPLOAD_SFTP_HOST             = ???
DHL_TO_VVC_SFTP_PATH             = ???
VVC_TO_DHL_SFTP_PATH             = ???
DHL_EXPORT_PREFIX                = ???

AVAILABLE_CUSTOMERS               = c01,c02,c03,c04
#                                  CustomerName;                JvmName;    ExportJobName;              UploadJobName;          ProcessIdentifier;      VcListPropName
#                                  --------------------------   ----------  -------------------------   ---------------------   -----------------
CUSTOMER_C01                     = C01;                         C01;        c01.deltaExport;            c01.deltaUpload;        EXPORT_CTE_TO_C01;      c01export
CUSTOMER_C02                     = C02;                         C02;        c02.deltaExport;            c02.deltaUpload;        EXPORT_CTE_TO_C02;      c02export
CUSTOMER_C03                     = C03;                         C03;        c03.deltaExport;            c03.deltaUpload;        EXPORT_CTE_TO_C03;      c03export
CUSTOMER_C04                     = C04;                         C04;        c04.deltaExport;            c04.deltaUpload;        EXPORT_CTE_TO_C04;      c04export
LAST_TEST_SOURCE = ITSQ
LAST_ITSQ_REVISION = ZWEI_PHASEN
LAST_LOAD_PATH = E:/Projekte/ClaudeCode/testsupport_client/X-TESTS
LAST_CFG_FILENAMES_LIST = 
LAST_CFG_FILENAME = E:/Projekte/ClaudeCode/testsupport_client/X-TESTS
LAST_UPLOAD_SYNTHETICS = false
LAST_USE_ONLY_TEST_CLZ = true
LAST_WINDOW_HEIGHT = 900
LAST_WINDOW_WIDTH = 1400
LAST_WINDOW_X_POS = 260
LAST_WINDOW_Y_POS = 66
LAST_LOOK_AND_FEEL_CLASS = javax.swing.plaf.metal.MetalLookAndFeel
